version: '3.9'
services:
  home-dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
      MAX_UPLOAD_KB: ${MAX_UPLOAD_KB:-512}
      DB_PATH: ${DB_PATH:-/data/app.db}
    volumes:
      - dashboard_data:/data
    restart: unless-stopped
volumes:
  dashboard_data:
